### ISSUE TITLE
Page is not Switching on Admin Dashboard

### ISSUE THREAD

**Issue by AnisH1427** [AnisH1427/Traffic-Management-System#4]
Hello contributor,
In a admin Dashboard, as we have multiple option for switching like a card layout, But the problem is the page is not switching. So, I kindly request our developer to fix this issue, Thank You.

**Comment by SagarBudhathoki** [comment]
done #8

**Comment by AnisH1427** [comment]
> 

Please donot confirm without fixing issue. The page still cannot be switched 
<img width="962" alt="image" src="https://user-images.githubusercontent.com/102788439/229037074-34c93262-c710-4e43-a9d4-d45356e9ef4b.png">

**Comment by SagarBudhathoki** [comment]
Dear @AnisH1427, Thank you for letting me know that the issue was not resolved earlier. I'm glad to inform you that the issue has been fixed now, and I can confirm that the page can be switched without any problems. Thank you for bringing it to my attention.
